--EXAMPLE QUERY: SELECT MIN(PRICE) FROM HOUSEPRICES_CA, HAVING MIN(PRICE) > 500000, WHERE PROVINCE NOT LIKE 'O'
SELECT MIN(PRICE) AS MINPRICE, PROVINCE, CITY
FROM [dbo].[HOUSEPRICES_CA]
WHERE PROVINCE NOT LIKE '%O%'
GROUP BY PROVINCE, CITY
HAVING MIN(PRICE) > 500000
ORDER BY MIN(PRICE)

--EXAMPLE QUERY: WHAT IS THE AVERAGE PRICE OF HOUSE IN USA YEAR BTWN 2015 AND 2016 GROUP BY HOUSEID TO GET FULL RESULTS. 
SELECT AVG(PRICE) AS AVG_PRICE
FROM [dbo].[HOUSEPRICES_USA]
WHERE YEAR BETWEEN '2015' AND '2020'
GROUP BY HOUSEID

--EXAMPLE QUERY: SELECT CANADA AND USA HOUSEPRICES, ALIAS BOTH NAMES, INNERJOIN BOTH TABLES, WHERE BOTH HOUSEPRICES GRTEQL 500000 ORDER BY CANADA PRICE
SELECT [dbo].[HOUSEPRICES_CA].PRICE AS HOUSEPRICE_CA, [dbo].[HOUSEPRICES_USA].PRICE AS HOUSEPRICE_USA
FROM [dbo].[HOUSEPRICES_CA] INNER JOIN [dbo].[HOUSEPRICES_USA]
ON [dbo].[HOUSEPRICES_CA].HOUSEID = [dbo].[HOUSEPRICES_USA].HOUSEID
WHERE [dbo].[HOUSEPRICES_CA].PRICE >= 500000 AND [dbo].[HOUSEPRICES_USA].PRICE >= 500000
ORDER BY [dbo].[HOUSEPRICES_CA].PRICE

SELECT MIN(PRICE) AS MINPRICE, PROVINCE, CITY
FROM [dbo].[HOUSEPRICES_CA]
WHERE PROVINCE NOT LIKE '%O%'
GROUP BY PROVINCE, CITY
HAVING MIN(PRICE) > 500000
ORDER BY MIN(PRICE)
