--SELECT MIN(PRICE) FROM HOUSEPRICES_CA, HAVING MIN(PRICE) > 500000, WHERE PROVINCE NOT LIKE 'O'
SELECT MIN(PRICE) AS MINPRICE, PROVINCE, CITY
FROM [dbo].[HOUSEPRICES_CA]
WHERE PROVINCE NOT LIKE '%O%'
GROUP BY PROVINCE, CITY
HAVING MIN(PRICE) > 500000
ORDER BY MIN(PRICE)