--EXAMPLE QUERY: SELECT MIN(PRICE) FROM HOUSEPRICES_CA, HAVING MIN(PRICE) > 500000, WHERE PROVINCE NOT LIKE 'O'
SELECT MIN(PRICE) AS MINPRICE, PROVINCE, CITY
FROM [dbo].[HOUSEPRICES_CA]
WHERE PROVINCE NOT LIKE '%O%'
GROUP BY PROVINCE, CITY
HAVING MIN(PRICE) > 500000
ORDER BY MIN(PRICE)

--EXAMPLE QUERY: WHAT IS THE AVERAGE PRICE OF HOUSE IN USA YEAR BTWN 2015 AND 2016 GROUP BY HOUSEID TO GET FULL RESULTS. 
SELECT AVG(PRICE) AS AVG_PRICE
FROM [dbo].[HOUSEPRICES_USA]
WHERE YEAR BETWEEN '2015' AND '2020'
GROUP BY HOUSEID
